# Generated by Django 3.0 on 2021-05-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="remaining_leaves",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No role"),
                    ("admin", "Admin"),
                    ("human_resource", "HR"),
                    ("teamlead", "Teamlead"),
                    ("developer", "Developer"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="total_leaves",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
